name: Deploy Streamlit App to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2 and build/run Docker
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.91.52.125 "
          mkdir -p ~/video-chatty &&
          rm -rf ~/video-chatty/*"
        scp -r ./* ubuntu@3.91.52.125:~/video-chatty/
        ssh ubuntu@3.91.52.125 "
          cd ~/video-chatty &&
          docker stop video-chatty || true &&
          docker rm video-chatty || true &&
          docker build -t video-chatty . &&
          docker run -d --name video-chatty -p 8501:8501 video-chatty
        "