name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t video-chatty-app .

    - name: Save Docker image to file
      run: docker save video-chatty-app | gzip > video-chatty-app.tar.gz

    - name: Copy Docker image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "video-chatty-app.tar.gz"
        target: "~/"

    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load -i ~/video-chatty-app.tar.gz
          docker stop video-chatty-app || true
          docker rm video-chatty-app || true
          docker run -d --name video-chatty-app -p 80:8501 video-chatty-app