name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ubuntu@3.91.52.125:/home/ubuntu/video-chatty

    - name: Install dependencies and restart app
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.91.52.125 << 'EOF'
          cd /home/ubuntu/video-chatty
          npm install --production
          pm2 restart all || pm2 start npm --name "video-chatty" -- start
        EOF